Improvements to error messages (#96)
Fixes https://github.com/cvc5/ethos/issues/94. Fixes
https://github.com/cvc5/ethos/issues/95.

Error on https://github.com/cvc5/ethos/issues/94 is now:
```
Error: /space/ajreynol/ethos/tc-fail.eo:11.54: Type checking application failed when applying la_generic
Children: [(! 1 :decimal), (! 1 :decimal)]
Message: Incorrect arity for la_generic, which expects 1 arguments and 0 premises but 2 arguments and 0 premises were provided
```
Error on https://github.com/cvc5/ethos/issues/95 is now:
```
Error: /space/ajreynol/ethos/tc-fail2.eo:6.3: Failed to bind symbol rule, since the symbol has already been defined